const genres=require("../routes/genre")
const rentals=require("../routes/rental")
const user=require("../routes/user")
const customers=require("../routes/customers")
const movies=require("../routes/movies")
const auth=require("../routes/auth")
const error=require("../middleware/error")
const express=require("express")
module.exports=function(app){
app.use(express.json())
app.use("/api/genres",genres)
app.use("/api/customers",customers)
app.use("/api/movies",movies)
app.use("/api/rentals",rentals)
app.use("/api/users",user)
app.use("/api/auth",auth)
app.use(error)
}